ndpp/applications/caja/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de la aplicacion
    url(
        r'^registrar-pagos/$',
        views.PaymentRegister.as_view(),
        name='add-payment'
    ),
    #url para listar diarios



    #rest de aplicacion recepcion
    url(r'^', include('applications.caja.url_services', namespace="caja_servis_url")),
]

ndpp/applications/recepcion/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de la aplicacion
    url(
        r'^guia-registrar/$',
        views.GuideRegisterView.as_view(),
        name='add-guide'
    ),
    #url para listar diarios
    url(
        r'^magazine-listar/$',
        views.MagazineListView.as_view(),
        name='list-magazine'
    ),
    #url para agregar diarios
    url(
        r'^magazine-add/$',
        views.MagazineCreate.as_view(),
        name='add-magazine'
    ),
    #url para agregar productos
    url(
        r'^prod-add/$',
        views.ProductCreate.as_view(),
        name='add-prod'
    ),
    #url para listar diarios
    url(
        r'^lista-dias-diarios/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.DaysTemplateView.as_view(),
        name='list_day-magazine'
    ),




    #rest de aplicacion recepcion
    url(r'^', include('applications.recepcion.url_services', namespace="recepcion_servis_url")),
]

ndpp/ndpp/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
#import debug_toolbar

urlpatterns = [
    #urls para usuario
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.miscelanea.urls', namespace="miscelanea_app")),
    url(r'^', include('applications.recepcion.urls', namespace="recepcion_app")),
    url(r'^', include('applications.caja.urls', namespace="caja_app")),

    url(r'^admin/', admin.site.urls),
]

ndpp/templates/include/header.html
<div class="header">
  <div id="togle-menu" class="icon-menu">

  </div>
  <div id="nav-menu" class="nav-menu">
    <ul class="menu-main">
      <li class="menu-item">
        <a href="#" class="menu-item__link">Home</a>
      </li>
      <li class="menu-item">
        <a href="{% url 'recepcion_app:list-magazine' %}" class="menu-item__link">Registro Diario</a>
      </li>
      <li class="menu-item">
        <a href="{% url 'recepcion_app:add-guide' %}" class="menu-item__link">Registro Guia</a>
      </li>
      <li class="menu-item">
        <a href="{% url 'caja_app:add-payment' %}" class="menu-item__link">Cobranza</a>
      </li>
      <li class="menu-item">
        <a href="#" class="menu-item__link">Reportes</a>
      </li>
      <li class="menu-item">
        <a href="#" class="menu-item__link">Administracion</a>
      </li>
      <li class="menu-item">
        <a href="#" class="menu-item__link__active">Salir</a>
      </li>
    </ul>
  </div>
  <a href="#" class="nav-menu___logo">DPP</a>
  <a href="#" class="icon-logout"></a>
</div>
<div class="space_head">

</div>