ndpp/applications/recepcion/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de la aplicacion
    url(
        r'^guia-registrar/$',
        views.GuideRegisterView.as_view(),
        name='add-guide'
    ),
    #url para listar diarios
    url(
        r'^magazine-listar/$',
        views.MagazineListView.as_view(),
        name='list-magazine'
    ),
    #url para agregar diarios
    url(
        r'^magazine-add/$',
        views.MagazineCreate.as_view(),
        name='add-magazine'
    ),
    #url para agregar productos
    url(
        r'^prod-add/$',
        views.ProductCreate.as_view(),
        name='add-prod'
    ),
    #url para listar diarios
    url(
        r'^lista-dias-diarios/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.DaysTemplateView.as_view(),
        name='list_day-magazine'
    ),




    #rest de aplicacion recepcion
    url(r'^', include('applications.recepcion.url_services', namespace="recepcion_servis_url")),
]

ndpp/ndpp/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
#import debug_toolbar

urlpatterns = [
    #urls para usuario
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.miscelanea.urls', namespace="miscelanea_app")),
    url(r'^', include('applications.recepcion.urls', namespace="recepcion_app")),
    url(r'^', include('applications.caja.urls', namespace="caja_app")),

    url(r'^admin/', admin.site.urls),
]

ndpp/applications/recepcion/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from .models import Magazine, MagazineDay, Guide, DetailGuide

from applications.miscelanea.models import Provider

class MagazineForm(forms.ModelForm):
    '''forulario para registrar un diario'''

    precio_tapa = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_guia = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_venta = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_tapad = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_guiad = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_ventad = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    class Meta:
        model = Magazine
        fields = (
            'name',
            'provider',
            'description',
        )
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombre',
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'placeholder': 'Descripcion',
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(MagazineForm, self).__init__(*args, **kwargs)
        self.fields['provider'].queryset = Provider.objects.filter(
            disable=False,
        )

    def clean_precio_tapa(self):
        precio_tapa = self.cleaned_data['precio_tapa']

        if precio_tapa < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_tapa', msj)
        else:
            return precio_tapa

    def clean_precio_guia(self):
        precio_guia = self.cleaned_data['precio_guia']

        if precio_guia < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_guia', msj)
        else:
            return precio_guia

    def clean_precio_venta(self):
        precio_venta = self.cleaned_data['precio_venta']

        if precio_venta < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_venta', msj)
        else:
            return precio_venta

    def clean_precio_tapad(self):
        precio_tapad = self.cleaned_data['precio_tapad']

        if precio_tapad < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_tapad', msj)
        else:
            return precio_tapad

    def clean_precio_guiad(self):
        precio_guiad = self.cleaned_data['precio_guiad']

        if precio_guiad < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_guiad', msj)
        else:
            return precio_guiad

    def clean_precio_ventad(self):
        precio_ventad = self.cleaned_data['precio_ventad']

        if precio_ventad < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_ventad', msj)
        else:
            return precio_ventad


class ProductAddForm(forms.ModelForm):
    '''formulario para registrar productos'''

    precio_tapa = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
                'ng-model':'vm.precio_tapa',
                'ng-change':'vm.calcular_precio(vm.tipo, vm.precio_tapa)',
            }
        )
    )
    precio_guia = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
                'ng-model':'vm.precio_guia',
            }
        )
    )
    precio_venta = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
                'ng-model':'vm.precio_venta',
            }
        )
    )
    class Meta:
        model = Magazine
        fields = (
            'name',
            'provider',
            'description',
            'afecto',
        )
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre',
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Descripcion',
                }
            ),
            'provider': forms.Select(
                attrs={'class': 'form-control input-sm'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(ProductAddForm, self).__init__(*args, **kwargs)
        self.fields['provider'].queryset = Provider.objects.filter(
            disable=False,
        )

    def clean_precio_tapa(self):
        precio_tapa = self.cleaned_data['precio_tapa']

        if precio_tapa < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_tapa', msj)
        else:
            return precio_tapa

    def clean_precio_guia(self):
        precio_guia = self.cleaned_data['precio_guia']

        if precio_guia < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_guia', msj)
        else:
            return precio_guia

    def clean_precio_venta(self):
        precio_venta = self.cleaned_data['precio_venta']

        if precio_venta < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_venta', msj)
        else:
            return precio_venta


class MagazineUpdateForm(forms.ModelForm):
    '''Formulario para modificar diarios'''

    precio_tapa = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_guia = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )
    precio_venta = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        widget=forms.NumberInput(
            attrs={
                'placeholder': '0.0',
            }
        )
    )

    class Meta:
        model = Magazine
        fields = (
            'name',
            'provider',
            'description',
        )
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombre',
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'placeholder': 'Descripcion',
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(MagazineUpdateForm, self).__init__(*args, **kwargs)
        self.fields['provider'].queryset = Provider.objects.filter(
            disable=False,
        )

    def clean_precio_tapa(self):
        precio_tapa = self.cleaned_data['precio_tapa']

        if precio_tapa < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_tapa', msj)
        else:
            return precio_tapa

    def clean_precio_guia(self):
        precio_guia = self.cleaned_data['precio_guia']

        if precio_guia < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_guia', msj)
        else:
            return precio_guia

    def clean_precio_venta(self):
        precio_venta = self.cleaned_data['precio_venta']

        if precio_venta < 0:
            msj = 'no puede tener un precio menor a cero'
            self.add_error('precio_venta', msj)
        else:
            return precio_venta

ndpp/applications/recepcion/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
    ListView,
    TemplateView,
    View,
)
from .models import (
    Magazine,
    MagazineDay,
    Guide,
    DetailGuide,
)

from .forms import (
    MagazineForm,
    ProductAddForm,
    MagazineUpdateForm,
)


class MagazineListView(TemplateView):
    """vista para listar producto o diario"""
    template_name = 'recepcion/magazine/list.html'


class MagazineCreate(CreateView):
    """vista para crear un diario"""
    form_class = MagazineForm
    success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/add.html'

    def form_valid(self, form):
        print '****************'
        #guardamos magazine y recuperaos objeto
        magazine = form.save(commit=False)
        magazine.user_created = self.request.user

        magazine.tipo = '0'
        magazine.afecto = True
        magazine.save()

        for dia in ['0','1','2','3','4','5']:
            magazine_dia1 = MagazineDay(
                magazine=magazine,
                day=dia,
                precio_tapa=form.cleaned_data['precio_tapa'],
                precio_guia=form.cleaned_data['precio_guia'],
                precio_venta=form.cleaned_data['precio_venta'],
                user_created=self.request.user,
            )
            magazine_dia1.save()

        #registro de producto dia-domingo
        magazine_dia2 = MagazineDay(
            magazine=magazine,
            day='6',
            precio_tapa=form.cleaned_data['precio_tapad'],
            precio_guia=form.cleaned_data['precio_guiad'],
            precio_venta=form.cleaned_data['precio_ventad'],
            user_created=self.request.user,
        )
        magazine_dia2.save()

        return super(MagazineCreate, self).form_valid(form)


class ProductCreate(CreateView):
    """vista para crear un prodcuto"""
    form_class = ProductAddForm
    success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/add_prod.html'

    def form_valid(self, form):
        #guardamos magazine y recuperaos objeto
        magazine = form.save(commit=False)
        magazine.user_created = self.request.user

        magazine.tipo = '1'
        magazine.save()

        #registro de produto lines-sabado
        magazine_dia1 = MagazineDay(
            magazine=magazine,
            day='7',
            precio_tapa=form.cleaned_data['precio_tapa'],
            precio_guia=form.cleaned_data['precio_guia'],
            precio_venta=form.cleaned_data['precio_venta'],
            user_created=self.request.user,
        )
        magazine_dia1.save()

        return super(ProductCreate, self).form_valid(form)


class DaysTemplateView(TemplateView):
    template_name = 'recepcion/magazine/days.html'

    def get_context_data(self, **kwargs):
        context = super(DaysTemplateView, self).get_context_data(**kwargs)
        lista_dias = {
            '0':'LUNES',
            '1':'MARTES',
            '2':'MIERCOLES',
            '3':'JUEVES',
            '4':'VIERNES',
            '5':'SABADO',
            '6':'DOMINGO',
        }
        days = sorted(lista_dias.items(), key=operator.itemgetter(0))
        context['days'] = days
        context['tipo'] = self.kwargs.get('tipo',0)
        context['pk'] = self.kwargs.get('pk',0)
        return context


class GuideRegisterView(TemplateView):
    """vista para registrar guias"""
    template_name = 'recepcion/guide/add.html'

ndpp/templates/recepcion/magazine/add.html
{% extends "recepcion/base_recepcion.html" %}

{% block title %}Agregar Diario{% endblock title %}

{% block content %}
  {% include "include/header.html" %}

  <!-- *************** REGISTRO DE MAGAZINE**************** -->
  <div class="callout">
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="grid-x grid-padding-x">
        <div class="medium-6 cell">
          <label>Nombre:
            {{form.name}}
          </label>
          {% for error in form.name.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-6 cell">
          <label>Proveedor
            {{form.provider}}
          </label>
          {% for error in form.provider.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-8 cell">
          <label>Descripcion:
            {{form.description}}
          </label>
          {% for error in form.description.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>

      <h3>Precios Lunes a Sabado</h3>
      <div class="grid-x grid-padding-x">

        <div class="medium-4 cell">
          <label> Precio Tapa:
            {{form.precio_tapa}}
          </label>
          {% for error in form.precio_tapa.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label>Precio Guia:
            {{form.precio_guia}}
          </label>
          {% for error in form.precio_guia.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label> Precio Venta:
            {{form.precio_venta}}
          </label>
          {% for error in form.precio_venta.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>

      <h3>Precios Domingo</h3>
      <div class="grid-x grid-padding-x">
        <div class="medium-4 cell">
          <label>Precio Tapa:
            {{form.precio_tapad}}
          </label>
          {% for error in form.precio_tapad.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label> Precio Guia:
            {{form.precio_guiad}}
          </label>
          {% for error in form.precio_guiad.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label>Precio Venta:
            {{form.precio_ventad}}
          </label>
          {% for error in form.precio_ventad.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>

      <input type="submit" class="button" value="Guardar">
    </form>
  </div>
{% endblock content %}

ndpp/templates/recepcion/magazine/add_prod.html
{% extends "recepcion/base_recepcion.html" %}

{% block title %}Agregar Producto{% endblock title %}

{% block content %}
  {% include "include/header.html" %}

  <!-- *************** REGISTRO DE MAGAZINE**************** -->
  <div class="callout">
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="grid-x grid-padding-x">
        <div class="medium-6 cell">
          <label>Nombre:
            {{form.name}}
          </label>
          {% for error in form.name.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-6 cell">
          <label>Proveedor
            {{form.provider}}
          </label>
          {% for error in form.provider.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-8 cell">
          <label>Descripcion:
            {{form.description}}
          </label>
          {% for error in form.description.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>

      <h3>Precios:</h3>
      <div class="grid-x grid-padding-x">

        <div class="medium-4 cell">
          <label> Precio Tapa:
            {{form.precio_tapa}}
          </label>
          {% for error in form.precio_tapa.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label>Precio Guia:
            {{form.precio_guia}}
          </label>
          {% for error in form.precio_guia.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
        <div class="medium-4 cell">
          <label> Precio Venta:
            {{form.precio_venta}}
          </label>
          {% for error in form.precio_venta.errors %}
            <div class="col-xs-12">
              <p class="text-alert">
                {{ error|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>

      <input type="submit" class="button" value="Guardar">
    </form>
  </div>
{% endblock content %}

ndpp/templates/recepcion/magazine/list.html
{% extends "recepcion/base_recepcion.html" %}

{% block title %}login DPP{% endblock title %}

{% block content %}
  {% include "include/header.html" %}
  <div class="callout">
    <a href="{% url 'recepcion_app:add-magazine' %}" class="button">Nuevo Diiario</a>
    <a href="{% url 'recepcion_app:add-prod' %}" class="button">Nuevo Producto</a>
  </div>
{% endblock content %}